// Country metadata for the 48 World Cup 2026 teams + a FIFA-3 -> ISO-2 map for
// club-league flags. Keys for TEAM_META are the exact team names as they appear
// in the Wikipedia squads wikitext. iso2 codes feed flagcdn.com (gb-eng etc.
// are flagcdn's regional codes). Confederations are the six FIFA confederations.

// [iso2, fifa3, confederation]
export const TEAM_META = {
  "Czech Republic":          ["cz",     "CZE", "UEFA"],
  "Mexico":                  ["mx",     "MEX", "CONCACAF"],
  "South Africa":            ["za",     "RSA", "CAF"],
  "South Korea":             ["kr",     "KOR", "AFC"],
  "Bosnia and Herzegovina":  ["ba",     "BIH", "UEFA"],
  "Canada":                  ["ca",     "CAN", "CONCACAF"],
  "Qatar":                   ["qa",     "QAT", "AFC"],
  "Switzerland":             ["ch",     "SUI", "UEFA"],
  "Brazil":                  ["br",     "BRA", "CONMEBOL"],
  "Haiti":                   ["ht",     "HAI", "CONCACAF"],
  "Morocco":                 ["ma",     "MAR", "CAF"],
  "Scotland":                ["gb-sct", "SCO", "UEFA"],
  "Australia":               ["au",     "AUS", "AFC"],
  "Paraguay":                ["py",     "PAR", "CONMEBOL"],
  "Turkey":                  ["tr",     "TUR", "UEFA"],
  "United States":           ["us",     "USA", "CONCACAF"],
  "Curaçao":                 ["cw",     "CUW", "CONCACAF"],
  "Ecuador":                 ["ec",     "ECU", "CONMEBOL"],
  "Germany":                 ["de",     "GER", "UEFA"],
  "Ivory Coast":             ["ci",     "CIV", "CAF"],
  "Japan":                   ["jp",     "JPN", "AFC"],
  "Netherlands":             ["nl",     "NED", "UEFA"],
  "Sweden":                  ["se",     "SWE", "UEFA"],
  "Tunisia":                 ["tn",     "TUN", "CAF"],
  "Belgium":                 ["be",     "BEL", "UEFA"],
  "Egypt":                   ["eg",     "EGY", "CAF"],
  "Iran":                    ["ir",     "IRN", "AFC"],
  "New Zealand":             ["nz",     "NZL", "OFC"],
  "Cape Verde":              ["cv",     "CPV", "CAF"],
  "Saudi Arabia":            ["sa",     "KSA", "AFC"],
  "Spain":                   ["es",     "ESP", "UEFA"],
  "Uruguay":                 ["uy",     "URU", "CONMEBOL"],
  "France":                  ["fr",     "FRA", "UEFA"],
  "Iraq":                    ["iq",     "IRQ", "AFC"],
  "Norway":                  ["no",     "NOR", "UEFA"],
  "Senegal":                 ["sn",     "SEN", "CAF"],
  "Algeria":                 ["dz",     "ALG", "CAF"],
  "Argentina":               ["ar",     "ARG", "CONMEBOL"],
  "Austria":                 ["at",     "AUT", "UEFA"],
  "Jordan":                  ["jo",     "JOR", "AFC"],
  "Colombia":                ["co",     "COL", "CONMEBOL"],
  "DR Congo":                ["cd",     "COD", "CAF"],
  "Portugal":                ["pt",     "POR", "UEFA"],
  "Uzbekistan":              ["uz",     "UZB", "AFC"],
  "Croatia":                 ["hr",     "CRO", "UEFA"],
  "England":                 ["gb-eng", "ENG", "UEFA"],
  "Ghana":                   ["gh",     "GHA", "CAF"],
  "Panama":                  ["pa",     "PAN", "CONCACAF"],
};

// FIFA-3 league codes used in `clubnat=` -> ISO-2 for flagcdn.
export const FIFA3_TO_ISO2 = {
  ENG: "gb-eng", SCO: "gb-sct", WAL: "gb-wls", IRL: "ie",
  GER: "de", ESP: "es", FRA: "fr", ITA: "it", NED: "nl", POR: "pt",
  BEL: "be", TUR: "tr", USA: "us", KSA: "sa", BRA: "br", QAT: "qa",
  MEX: "mx", IRN: "ir", CZE: "cz", EGY: "eg", RSA: "za", ARG: "ar",
  UZB: "uz", UAE: "ae", IRQ: "iq", DEN: "dk", SUI: "ch", RUS: "ru",
  GRE: "gr", JOR: "jo", CYP: "cy", NZL: "nz", KOR: "kr", TUN: "tn",
  NOR: "no", JPN: "jp", AUT: "at", AUS: "au", CRO: "hr", CAN: "ca",
  POL: "pl", ECU: "ec", SWE: "se", ISR: "il", PAR: "py", MAS: "my",
  MAR: "ma", HUN: "hu", ALG: "dz", VEN: "ve", SVN: "si", SVK: "sk",
  SRB: "rs", ROU: "ro", PAN: "pa", CRC: "cr", CHI: "cl", BUL: "bg",
  URU: "uy", THA: "th", KAZ: "kz", IDN: "id", HON: "hn", HAI: "ht",
  GHA: "gh", FIN: "fi", COL: "co", CHN: "cn", BIH: "ba", AZE: "az",
  ARM: "am",
};

// Full league/country names for `clubnat` (used as a hint label).
export const FIFA3_TO_NAME = {
  ENG: "England", SCO: "Scotland", WAL: "Wales", IRL: "Ireland",
  GER: "Germany", ESP: "Spain", FRA: "France", ITA: "Italy",
  NED: "Netherlands", POR: "Portugal", BEL: "Belgium", TUR: "Turkey",
  USA: "United States", KSA: "Saudi Arabia", BRA: "Brazil", QAT: "Qatar",
  MEX: "Mexico", IRN: "Iran", CZE: "Czechia", EGY: "Egypt",
  RSA: "South Africa", ARG: "Argentina", UZB: "Uzbekistan",
  UAE: "United Arab Emirates", IRQ: "Iraq", DEN: "Denmark",
  SUI: "Switzerland", RUS: "Russia", GRE: "Greece", JOR: "Jordan",
  CYP: "Cyprus", NZL: "New Zealand", KOR: "South Korea", TUN: "Tunisia",
  NOR: "Norway", JPN: "Japan", AUT: "Austria", AUS: "Australia",
  CRO: "Croatia", CAN: "Canada", POL: "Poland", ECU: "Ecuador",
  SWE: "Sweden", ISR: "Israel", PAR: "Paraguay", MAS: "Malaysia",
  MAR: "Morocco", HUN: "Hungary", ALG: "Algeria", VEN: "Venezuela",
  SVN: "Slovenia", SVK: "Slovakia", SRB: "Serbia", ROU: "Romania",
  PAN: "Panama", CRC: "Costa Rica", CHI: "Chile", BUL: "Bulgaria",
  URU: "Uruguay", THA: "Thailand", KAZ: "Kazakhstan", IDN: "Indonesia",
  HON: "Honduras", HAI: "Haiti", GHA: "Ghana", CHN: "China",
  FIN: "Finland", COL: "Colombia",
  BIH: "Bosnia and Herzegovina", AZE: "Azerbaijan", ARM: "Armenia",
};
